### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by xayoung** [spacemeowx2/switch-lan-play#78]
Ubuntu Server 16.04.1 LTS 64
node version: v8.17.0
npm  version: 6.13.4

ubuntu@VM-229-147-ubuntu:~$ sudo docker run -d -p 11451:11451/udp -p 11451:11451/tcp spacemeowx2/switch-lan-play
ae7d942a18811ef7c73833689fe093aad7ff174344985282de7ab070ba7b1a16
ubuntu@VM-229-147-ubuntu:~$ cd switch-lan-play/server/
ubuntu@VM-229-147-ubuntu:~/switch-lan-play/server$ npm start
> switch-lan-play@1.0.0-alpha.2 start /home/ubuntu/switch-lan-play/server
> node dist/main.js
server error:
Error: bind EADDRINUSE :::11451
    at _handle.lookup (dgram.js:266:18)
    at lookup6 (/home/ubuntu/switch-lan-play/server/dist/udpserver.js:62:5)
    at UDP.lookup6 (dgram.js:58:10)
    at Socket.bind (dgram.js:223:16)
    at new SLPServer (/home/ubuntu/switch-lan-play/server/dist/udpserver.js:138:16)
    at main (/home/ubuntu/switch-lan-play/server/dist/main.js:23:13)
    at Object.<anonymous> (/home/ubuntu/switch-lan-play/server/dist/main.js:27:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
/home/ubuntu/switch-lan-play/server/dist/udpserver.js:284
        this.server.close();
                    ^
TypeError: Cannot read property 'close' of undefined
    at SLPServer.onError (/home/ubuntu/switch-lan-play/server/dist/udpserver.js:284:21)
    at Socket.SLPServer.server.on (/home/ubuntu/switch-lan-play/server/dist/udpserver.js:135:42)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at _handle.lookup (dgram.js:267:14)
    at lookup6 (/home/ubuntu/switch-lan-play/server/dist/udpserver.js:62:5)
    at UDP.lookup6 (dgram.js:58:10)
    at Socket.bind (dgram.js:223:16)
    at new SLPServer (/home/ubuntu/switch-lan-play/server/dist/udpserver.js:138:16)
    at main (/home/ubuntu/switch-lan-play/server/dist/main.js:23:13)

**Comment by spacemeowx2** [comment]
`EADDRINUSE :::11451` means you already bind to port 11451. Close previous one and try again
