### ISSUE TITLE
Rock64 support (stretch armhf) ?

### ISSUE THREAD

**Issue by S3phi40T** [spacemeowx2/switch-lan-play#9]
Hello,

I have tried running the server but it doesn't work for me. Can you give me some ideas how to run it?
Installed nodejs and npm:
http://linuxbsdos.com/2017/06/26/how-to-install-node-js-lts-on-debian-9-stretch/

Log file attached:

```
GNU nano 2.7.4                                                           File: /srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'server' ]
2 info using npm@3.10.10
3 info using node@v6.14.4
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle switch-lan-play@1.0.0-alpha.2~preserver: switch-lan-play@1.0.0-alpha.2
6 silly lifecycle switch-lan-play@1.0.0-alpha.2~preserver: no script for preserver, continuing
7 info lifecycle switch-lan-play@1.0.0-alpha.2~server: switch-lan-play@1.0.0-alpha.2
8 verbose lifecycle switch-lan-play@1.0.0-alpha.2~server: unsafe-perm in lifecycle true
9 verbose lifecycle switch-lan-play@1.0.0-alpha.2~server: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/loc$
10 verbose lifecycle switch-lan-play@1.0.0-alpha.2~server: CWD: /srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server
11 silly lifecycle switch-lan-play@1.0.0-alpha.2~server: Args: [ '-c', 'node dist/udpserver.js' ]
12 silly lifecycle switch-lan-play@1.0.0-alpha.2~server: Returned: code: 1  signal: null
13 info lifecycle switch-lan-play@1.0.0-alpha.2~server: Failed to exec server script
14 verbose stack Error: switch-lan-play@1.0.0-alpha.2 server: `node dist/udpserver.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid switch-lan-play@1.0.0-alpha.2
16 verbose cwd /srv/dev-disk-by-label-Malinka-Media/Home/sephirot/switch-lan-play/server
17 error Linux 4.4.132-1075-rockchip-ayufan-ga83beded8524
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
19 error node v6.14.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error switch-lan-play@1.0.0-alpha.2 server: `node dist/udpserver.js`
22 error Exit status 1
23 error Failed at the switch-lan-play@1.0.0-alpha.2 server script 'node dist/udpserver.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the switch-lan-play package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/udpserver.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs switch-lan-play
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls switch-lan-play
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by spacemeowx2** [comment]
I can't get enough information, is there any more logs prints to the screen?

**Comment by S3phi40T** [comment]
Solved by myself after exactly the same erorr under Windows ;)
`npm run build `
should be run not only if build change but also before first run :)
Please update readme file :)
